apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
  labels:
    app: app-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
    spec:
      containers:
        - name: app
          image: nginx:alpine
          command: ["/bin/sh", "-c", "echo 'VERSION: v1' > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
