apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stockwise.frontendName" . }}
  labels:
    {{- include "stockwise.labels" . | nindent 4 }}
    {{- include "stockwise.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "stockwise.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stockwise.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "stockwise.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_URL
              value: "http://{{ include "stockwise.backendName" . }}:{{ .Values.backend.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- include "stockwise.containerSecurity" . | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stockwise.frontendName" . }}
  labels:
    {{- include "stockwise.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stockwise.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
